# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dojo < Formula
  desc ""
  homepage ""
  version "0.0.23"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.23/dojoctl_0.0.23_Darwin_x86_64.tar.gz"
    sha256 "b2f73903567b3bb9cf88c47695136039c1c50f6748409ac00dc8172f73504942"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.23/dojoctl_0.0.23_Darwin_arm64.tar.gz"
    sha256 "0bca5dffa43fad7594fa0e8938cd0397518b10c46635d510ca2a6a2b55507d5a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.23/dojoctl_0.0.23_Linux_x86_64.tar.gz"
    sha256 "f779c6fa54e42b6267b62f61b1e5680963a9caf6019b961f0d2ec649fd6e5333"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.23/dojoctl_0.0.23_Linux_armv6.tar.gz"
    sha256 "0ce612f23765cf1eb4d69106e8fddcff312b285a1faa63612ec32f74ca07aee5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.23/dojoctl_0.0.23_Linux_arm64.tar.gz"
    sha256 "14fd2097c7b2f093d0a6c010aab5e31b5d12515ad38acb7ce0d5f2f53b3e8ed5"
  end

  def install
    bin.install "dojoctl"
  end
end
