# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dojo < Formula
  desc ""
  homepage ""
  version "0.0.15"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.15/dojoctl_0.0.15_Darwin_x86_64.tar.gz"
    sha256 "0424f4a8963b1be62e10f5ee24c6b725e235ed8e175521594188164af4532f4f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.15/dojoctl_0.0.15_Darwin_arm64.tar.gz"
    sha256 "67d1b71b8657c836044db615aa625a9e725d3305a7cc9cf775b512dfd08ab697"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.15/dojoctl_0.0.15_Linux_x86_64.tar.gz"
    sha256 "ada87b4bc465050c8cb60f852616beaeba326472cb4523b6a590e1d434ceb77f"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.15/dojoctl_0.0.15_Linux_armv6.tar.gz"
    sha256 "e9afe44ee9694e91e3328fa6544b78dae64016d89ee673032ba08dc499645bd5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/zengineDev/dojo/releases/download/v0.0.15/dojoctl_0.0.15_Linux_arm64.tar.gz"
    sha256 "f37bde577c6a8a82245a8a75661d30623e4064d2052beac25ae1ff6fa1bb6f3c"
  end

  def install
    bin.install "dojoctl"
  end
end
